###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum

from pydantic import BaseModel, ConfigDict

from typing_extensions import TypeAlias, Literal
from typing import Dict, Generic, List, Optional, TypeVar, Union

from . import types
from .types import Checked, Check

###############################################################################
#
#  These types are used for streaming, for when an instance of a type
#  is still being built up and any of its fields is not yet fully available.
#
###############################################################################

T = TypeVar('T')
class StreamState(BaseModel, Generic[T]):
    value: T
    state: Literal["Pending", "Incomplete", "Complete"]


class CompletionHalt(BaseModel):
    reason: Optional[str] = None

class ContextBlock(BaseModel):
    prompt: Optional[str] = None
    limit: Optional[int] = None
    generated: Optional[str] = None

class Error(BaseModel):
    reason: Optional[str] = None

class InitBlock(BaseModel):
    prompt: Optional[str] = None
    limit: Optional[int] = None

class Punctuate(BaseModel):
    reason: Optional[str] = None

class Response(BaseModel):
    word: Optional[str] = None

class SentenceResponse(BaseModel):
    sentence: Optional[str] = None
